services:
  auth-service:
    image: ghcr.io/vkirs229037/mag_auth:latest:local
    volumes:
      - ../environments/auth-service/config.dev.yaml:/app/config.yaml:ro
    environment:
      - SQLALCHEMY_DATABASE_URI=sqlite:///dev.db
      - SECRET_KEY=12345678
    networks:
      - app-net

  search-service:
    image: ghcr.io/vkirs229037/mag_search:latest
    volumes:
      - ../environments/search-service/config.dev.yaml:/app/config.yaml:ro
    networks:
      - app-net

  frontend:
    image: ghcr.io/vkirs229037/mag_front:latest
    # конфиг уже в образе (nginx-frontend.conf)
    networks:
      - app-net

  nginx-proxy:
    image: nginx-proxy:local
    ports:
      - "80:80"
    networks:
      - app-net
    depends_on:
      - auth-service
      - search-service
      - frontend

networks:
  app-net:
