upstream auth_service {
    server auth-service:5000;
}
upstream search_service {
    server search-service:5000;
}
upstream frontend {
    server frontend:80;
}

server {
    listen 80;
    server_name _;
    error_log /var/log/nginx/error.log debug;

    location /api/auth/ {
        proxy_pass http://auth_service;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/search/ {
        proxy_pass http://search_service;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        proxy_pass http://frontend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
