upstream auth_service {
    server auth-service:5000;
}
upstream search_service {
    server search-service:5000;
}

server {
    listen 80;
    server_name localhost;

    location /api/auth-service/ {
        proxy_pass http://auth_service/; # дальше уже вызывается корень микросервиса
    }
    location /api/search-service/ {
        proxy_pass http://search_service/;
    }
    location / {
        proxy_pass http://frontend:80;
    }
}